<script>
  var script = document.createElement('script');
  script.src = 'https://cdn.live2.ai/assets/sdk/latest/live2ai-embed-sdk.js';
  script.defer = true;
  // script.async = true;
  document.head.appendChild(script);
</script>

<div data-live2-embed="1" data-live2-picked-up="0" data-live2-loaded="0"
  data-live2-embed-id="<?php echo $block->getData('embed_id'); ?>">
  <div class="live2-container"></div>
  <div class="live2-custom-css" style="display: none !important"></div>
</div>


