<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $currentCurrency = $storeManager->getStore()->getCurrentCurrencyCode();
?>
<div
  data-live2-social-wall-embed="1"
  data-live2-social-wall-picked-up="0"
  data-live2-social-wall-loaded="0"
  data-live2-social-wall-embed-id="<?php echo $block->getData('embed_id'); ?>"
  data-live2-social-wall-team-id="6618d9932fa8618399f3d956"
  data-live2-product="socialwall"
  data-live2-selected-currency="<?php echo $currentCurrency; ?>"
>
  <div class="live2-container"></div>
  <div class="live2-custom-css" style="display: none !important"></div>
</div>



<script src="https://storage.googleapis.com/assets-live2ai-prod/assets/social-wall-sdk/latest/live2ai-embed-sdk.js?v=164"></script>
